apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: crossfits-acme
spec:
  acme:
    email: CHANGEME
    server: https://172.16.8.50/acme/acme/directory
    privateKeySecretRef:
      name: clusterissuer-key
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlCcERDQ0FVcWdBd0lCQWdJUkFNblBsUDBzY3dYSG5CS2l5OUNsbElVd0NnWUlLb1pJemowRUF3SXdNREVTDQpNQkFHQTFVRUNoTUpRMUp2VTFOR1NWUnpNUm93R0FZRFZRUURFeEZEVW05VFUwWkpWSE1nVW05dmRDQkRRVEFlDQpGdzB5TWpFeE16QXhOVEl4TUROYUZ3MHpNakV4TWpjeE5USXhNRE5hTURBeEVqQVFCZ05WQkFvVENVTlNiMU5UDQpSa2xVY3pFYU1CZ0dBMVVFQXhNUlExSnZVMU5HU1ZSeklGSnZiM1FnUTBFd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxDQpoa2pPUFFNQkJ3TkNBQVN2VmxrR2REbS9LbXNkT3lQcG9hOG5xOEhWb0VTK0hoWEYyL2U1MFRpUlI1bnI4MnBoDQpNRTJxN1k4MlRsMng1Q0swL0JObnJ6Qi9EYW9aenhiaFlQT09vMFV3UXpBT0JnTlZIUThCQWY4RUJBTUNBUVl3DQpFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBVEFkQmdOVkhRNEVGZ1FVeTFvbk95Q3R5NGdnRUg5TjNRbk9kMkVVDQp5NW93Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU01VkFRUk94TkVlR0prMWxUUHJPZ2pZcVRBR2VkbDVDOC9SDQpXU3hiRXdQaUFpQUlWRld3M0wxWWhjTHE1UW82eGpreC9scEtsekcvNzVtY0VuOUxyWDNZWUE9PQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx